version: "3"

services:
  mongodb:
    container_name: robots-mongodb
    image: mongo:5.0.3
    ports:
      - "27017:27017"
    networks:
      martian-robots:

  nodejs:
    container_name: robots-api
    image: migue9b/martian-api:1.0
    ports:
      - "80:80"
    networks:
      martian-robots:

networks:
  martian-robots:
